### ISSUE TITLE
Utilizar a tag sup do html em vez de ^2

### ISSUE THREAD

**Issue by Rodrigo19Silva** [ricardo-santos-a22207422/ricardo-santos-a22207422.github.io#1]
https://github.com/ricardo-santos-a22207422/ricardo-santos-a22207422.github.io/blob/d9e9bdbf292f92e17eff1590cc0337f20e759776/Lab2/info.html#L33

**Comment by ricardo-santos-a22207422** [comment]
Fixed, obrigado
